---

- name: Deploy Rancher on Kubernetes cluster
  hosts: mgmt
  pre_tasks:
    - name: Get kube config file content from Kubernetes master node
      ansible.builtin.slurp:
        src: ~/.kube/config
      register: kubeconfig
      delegate_to: "{{ groups['kubemaster'][0] }}"
    - name: Write kube config file content to localhost
      ansible.builtin.copy:
        content: "{{ kubeconfig['content'] | b64decode }}"
        dest: "/tmp/.kube-config"
        mode: '0600'
  roles:
    - helm
    - rancher
