---

# See https://cert-manager.io/docs/installation/kubernetes/#installing-with-helm
- name: Add Jetstack Helm chart repository for cert-manager
  community.kubernetes.helm_repository:
    name: "jetstack"
    repo_url: "https://charts.jetstack.io"

- name: Create namespace for cert-manager
  community.kubernetes.k8s:
    name: cert-manager
    api_version: v1
    kind: Namespace
    kubeconfig: /tmp/.kube-config
    state: present

- name: Install cert-manager from Helm repository
  community.kubernetes.helm:
    name: cert-manager
    chart_ref: jetstack/cert-manager
    release_namespace: cert-manager
    update_repo_cache: true
    kubeconfig: /tmp/.kube-config
    values:
      installCRDs: true
    wait: yes
    state: present